export const SET_IS_FIRST_TIME_RUNNING = 'SET_IS_FIRST_TIME_RUNNING';
export const SET_EMAIL_VALIDATE = 'SET_EMAIL_VALIDATE';
export const SET_MOBILE_VALIDATE = 'SET_MOBILE_VALIDATE';
export const SET_IS_USER_LOGGED = 'SET_IS_USER_LOGGED';
export const SET_USER_INOFORMATION = 'SET_USER_INOFORMATION';
export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';
export const SET_FILTER_ELEMENT = 'SET_FILTER_ELEMENT';
export const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE';
